config/routes.rb
Rails.application.routes.draw do

  get 'courses', to: "courses#index", as: 'courses'
  get 'services', to: 'services#index', as: 'services'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'about', to: 'pages#about', as: 'about'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="col">
        <h5><b>Moon Nails Eyebrows Eyelashes</b></h5>
        <br/>
        <p>Tel. 090 397 01 77 | xcherryx82@yahoo.com</p>
        <p>212D Trần Hưng Đạo, P Nguyễn Cư Trinh, Q1, TP Hồ Chí Minh</p>
      </div>
      <div class="col social-icons d-flex flex-row justify-content-around pt-5">
        <div class="youtube">Youtube</div>
        <div class="facebook">Facebook</div>
        <div class="instagram">Instagram</div>  
      </div>
    </div>
    <div class="footer-logo text-center">
      <%= image_tag("https://res.cloudinary.com/buihdk/image/upload/v1538552374/logo_Moon.png", width: "200px", alt: "footer-logo") %>
    </div>
  </div>
  <div class="hotline">
    <%= image_tag("https://res.cloudinary.com/buihdk/image/upload/v1538552354/ic_phone_in_talk_copy.svg") %>
    <span>Hotline: 0912 141 241</span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light fixed-top border-bottom box-shadow">
    <div class="container">
        <a class="navbar-brand" href="">
            <img src="https://placeimg.com/100/100/tech" alt="logo-circle" width="50px;">
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">Trang chủ</a></li>
                <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">Giới thiệu</a></li>
                <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">Dịch vụ</a></li>
                <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">Đào tạo</a></li>
                <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">Shop</a></li>
                <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">Liên hệ</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">Cart</a></li>
                <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">VN</a></li>
            </ul>
        </div>
    </div>
  </nav>
  <img src="https://placeimg.com/300/500/people" class="banner-portrait" alt="banner-portrait">
  <h2 class="banner-text text-center">Master Nghi Nguyễn</h2>
  <div class="banner-text-wrap">
    <div class="running-text">MOON EYES BROWN EYE SPLASH NAIL</div>
    <div class="running-text">MOON EYES BROWN EYE SPLASH NAIL</div>
    <div class="running-text">MOON EYES BROWN EYE SPLASH NAIL</div>
  </div>
</header>

app/views/layouts/_navigation_b.html.erb
<main class="nav-black">
  <nav class="navbar navbar-expand-lg border-bottom">
    <div class="container">
      <a class="navbar-brand" href="http://localhost:3000/">
        <img src="https://res.cloudinary.com/buihdk/image/upload/v1538840205/M-logo-white.png" alt="logo-circle" width="50px;">
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= root_path %>">Trang chủ</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= about_path %>">Giới thiệu</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= services_path + "?page=2"%>">Dịch vụ</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= courses_path %>">Đào tạo</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">Shop</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= contact_path %>">Liên hệ</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">Cart</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">VN</a></li>
        </ul>
      </div>
    </div>
  </nav>
</main>

app/views/layouts/_navigation_black.html.erb
<section id="nav-black">
  <nav class="navbar navbar-expand-lg border-bottom">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">
        <%= image_tag("https://res.cloudinary.com/buihdk/image/upload/v1538840205/M-logo-white.png", alt: "logo-circle", width: "50px") %>
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= root_path %>">Trang chủ</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= about_path %>">Giới thiệu</a></li>
          <li class="nav-item ml-5 pt-1">
            <div class="dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dịch vụ
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="nav-link" href="<%= services_path + "?page=1"%>">Moon Eye Brown</a>
                <a class="nav-link" href="<%= services_path + "?page=2"%>">Moon Eyelashes</a>
                <a class="nav-link" href="<%= services_path + "?page=3"%>">Dịch vụ Nails</a>
              </div>
            </div>
          </li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= courses_path %>">Đào tạo</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">Shop</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= contact_path %>">Liên hệ</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">Cart</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">VN</a></li>
        </ul>
      </div>
    </div>
  </nav>
</section>

app/views/layouts/_navigation_w.html.erb
<main class="nav-white">
  <nav class="navbar navbar-expand-lg border-bottom">
    <div class="container">
      <a class="navbar-brand" href="">
        <img src="https://res.cloudinary.com/buihdk/image/upload/v1538552355/Group.png" alt="logo-circle" width="50px;">
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= root_path %>">Trang chủ</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= about_path %>">Giới thiệu</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= services_path + "?page=2"%>">Dịch vụ</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= courses_path %>">Đào tạo</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">Shop</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= contact_path %>">Liên hệ</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">Cart</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">VN</a></li>
        </ul>
      </div>
    </div>
  </nav>
</main>

app/views/layouts/_navigation_white.html.erb
<section id="nav-white">
  <nav class="navbar navbar-expand-lg border-bottom">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">
        <%= image_tag("https://res.cloudinary.com/buihdk/image/upload/v1538552355/Group.png", alt: "logo-circle", width: "50px") %>
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= root_path %>">Trang chủ</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= about_path %>">Giới thiệu</a></li>
          <li class="nav-item ml-5 pt-1">
            <div class="dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dịch vụ
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="nav-link" href="<%= services_path + "?page=1"%>">Moon Eye Brown</a>
                <a class="nav-link" href="<%= services_path + "?page=2"%>">Moon Eyelashes</a>
                <a class="nav-link" href="<%= services_path + "?page=3"%>">Dịch vụ Nails</a>
              </div>
            </div>
          </li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= courses_path %>">Đào tạo</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">Shop</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="<%= contact_path %>">Liên hệ</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">Cart</a></li>
          <li class="nav-item ml-5 pt-1"><a class="nav-link" href="#">VN</a></li>
        </ul>
      </div>
    </div>
  </nav>
</section>